spring.application.name=server
server.port=${PORT:8080} #use port env variable if it exists, otherwise use 8080 (serves as a loopback by render )
server.address=0.0.0.0 #listen on loopback and external interfaces

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}